### ISSUE TITLE
Have DT app useable in many languages

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#156] opened 2019-12-10 19:05 UTC
The app works by default in English. It will be ideal to have it useable in other languages too.

Translations so far: 

- [x] English
- [x] Spanish
- [x] Turkish
- [x] Arabic
- [ ] Portuguese
- [ ] German
- [ ] French

What other languages should be done?

**Comment by zdmc23** [comment] 2019-12-13 01:30
@mikeallbutt I've added a few languages via the Automatic Translation feature of POEditor (I spent a few $ to get a bunch of AT character credits).  I realize that these are likely to be unreliable translations, but we can leave them as starters until we find someone to properly review

Also, is this Issue a duplicate of #67 ?

**Comment by mikeallbutt** [comment] 2019-12-13 18:09
> @mikeallbutt I've added a few languages via the Automatic Translation feature of POEditor (I spent a few $ to get a bunch of AT character credits). I realize that these are likely to be unreliable translations, but we can leave them as starters until we find someone to properly review
> 
> Also, is this Issue a duplicate of #67 ?

Thanks @zdmc23 for setting up those other languages. 

This is not a duplicate issue of #67 but are related. It seems though that we can't offer all these languages until they are available on the DT website, because that is where the setting for the user is obtained from. If a user selects a language on the login screen ie. German, but that language isn't what they have set in their DT settings - then what happens? What language does the interface display in?

**Comment by zdmc23** [comment] 2020-04-28 02:43
Resolved by https://github.com/DiscipleTools/disciple-tools-mobile-app/commit/9314857870693b35407bbcaed648012366c0e5a3

**Closed by zdmc23** 2020-04-28 02:43 UTC
Labels: feature
