### ISSUE TITLE
New comment entry should allow multiple lines of text

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#35] opened 2019-09-02 13:35 UTC
MexSurfer:
> When writing a new comment, touching the return key closed the keyboard, instead of moving the cursor down 1 line.

It might be best to change this field to a multi-line text field in order to allow line breaks within it. This is common within messaging apps now.

**Comment by mikeallbutt** [comment] 2019-10-23 19:05
This functions (sort of) correctly when adding a new contact and writing in the "Initial Comment" field. The issue is also that the field doesn't move up as it increases in size, so it ends up being below the keyboard. 

In all other places where comments can be written, the field is a single line so multiple lines can't be written.

**Comment by cairocoder01** [comment] 2019-10-24 10:04
## Requirements ##
* When entering a new comment on an existing contact, the text field should allow multiple lines of text
  * Field should be changed to a multiline instead of single-line input
  * When using enter/return key on keyboard, a line break should be added (instead of closing the keyboard)
  * Input field should expand in height as more lines of text are added. However, it should only expand up to 6 lines of text (based on WhatsApp's same feature)

**Comment by jl0325** [comment] 2019-11-19 17:45
Multiline on new commet available!

![IMG-20191119-WA0014](https://user-images.githubusercontent.com/10079527/69171676-673ddb00-0aca-11ea-9b78-66f5e199ca0b.jpg)
![IMG-20191119-WA0013](https://user-images.githubusercontent.com/10079527/69171677-673ddb00-0aca-11ea-8e41-b0ea0c35da55.jpg)

**Comment by zdmc23** [comment] 2019-11-19 19:30
Verified, although we may want to open a new issue for the keyboard covering the text field and bc it’s too easy to double submit a comment due to delay on first click of submit comment button

![3603C104-B46A-4DC3-9BD8-35D98CEF8DFD](https://user-images.githubusercontent.com/191707/69179193-213c4380-0ad9-11ea-9c94-5931b5facba0.png)

**Comment by zdmc23** [comment] 2019-11-23 15:59
We want this to also be implemented for Group Comments:

![488DC1D0-745C-426F-B1BC-9C658608593C](https://user-images.githubusercontent.com/191707/69480750-2995c680-0dd8-11ea-99b1-0bb37fc450c6.png)

**Comment by zdmc23** [comment] 2019-11-23 16:01
Same with the fix to not cover the Text Input field; it should have the same implementation for Groups:

![F9ACBD20-1898-4F40-8F59-99791D8EAFD9](https://user-images.githubusercontent.com/191707/69480748-2995c680-0dd8-11ea-8aa1-f065193d2858.png)

**Comment by jl0325** [comment] 2019-11-25 13:03
@zdmc23, Can you give info about your testing phone?

**Comment by zdmc23** [comment] 2019-11-25 14:50
Hi @jl0325 , I use an iPhone XR.  Multi-line comments work as expected for `Contact` "Comments and Activities", but we also need that same code merged into the `Group` "Comments and Activities"

**Comment by jl0325** [comment] 2019-11-25 15:15
Hi @zdmc23, I updated to support SafeArea on IOS. And added this function on Group. 

I would like you to test on a physical device with this resolution, I did the test on the simulator of iphone 11 pro max.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-25 at 10 03 36](https://user-images.githubusercontent.com/10079527/69552239-1f0c3600-0f6c-11ea-802a-46aa2140afaa.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-25 at 10 03 30](https://user-images.githubusercontent.com/10079527/69552240-1f0c3600-0f6c-11ea-8b6d-ede8a962a6b1.png)

**Comment by zdmc23** [comment] 2019-11-25 15:19
Hi @jl0325 , sure, please issue a new PR for the changes and I'll merge them and test via Expo on my device

**Comment by jl0325** [comment] 2019-11-25 15:23
> Hi @jl0325 , sure, please issue a new PR for the changes and I'll merge them and test via Expo on my device

New PR done. Thx!

**Closed** 2019-11-25 15:27 UTC
Labels: enhancement, help wanted

**Comment by zdmc23** [comment] 2019-11-25 15:46
Looks great!! (no more keyboard overlap), and works for both Groups and Contacts

![2BAEC417-CC57-4EC8-B8D4-70923627B578](https://user-images.githubusercontent.com/191707/69555211-d0ad6600-0f70-11ea-9844-07302e28b857.png)
