### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#67] opened 2019-10-24 18:43 UTC
Only show in the list of languages the ones that actually have data and will allow the app to function correctly in that chosen language.

![settings-languages](https://user-images.githubusercontent.com/43966676/67515429-3baf0880-f664-11e9-871a-6e9edf1e950b.png)

**Comment by zdmc23** [comment] 2019-10-25 04:23
Before we remove it, can we try to recruit folks to include the translations?  I don't think that there are more than 75 labels in the app, so we could probably also manually translate via an online lookup

**Comment by mikeallbutt** [comment] 2019-10-25 09:51
> Before we remove it, can we try to recruit folks to include the translations? I don't think that there are more than 75 labels in the app, so we could probably also manually translate via an online lookup

Good idea @zdmc23 to try and find translations first. So there are: 

- [ ] English
- [ ] Spanish
- [ ] French
- [ ] Turkish
- [ ] Arabic
- [ ] Chinese
- [ ] Other?

**Comment by mikeallbutt** [comment] 2019-10-26 02:51
What languages other than the ones previously listed should we try to get translated too?

[ ] Portuguese 
[ ] German 
[ ] Korean 
[ ] Japanese

**Comment by mrtmrcbr** [comment] 2019-10-28 10:06
Hi, I would like to add turkish translation for you.

https://github.com/DiscipleTools/disciple-tools-mobile-app/blob/master/languages/en.json
I will make a copy of this for turkish, is there any file to translate to turkish except that one

**Comment by mikeallbutt** [comment] 2019-10-28 21:11
How does the jason languages files stay updated when new words are added?

With DT the files are translated using POedit online. Is there a similar way to do this for the app, or is all the translatable text need to manually be added to each json file for each language?

**Comment by zdmc23** [comment] 2019-11-25 23:10
> How does the jason languages files stay updated when new words are added?
> 
> With DT the files are translated using Poedit online. Is there a similar way to do this for the app, or is all the translatable text need to manually be added to each json file for each language?

The JSON files need to be updated and kept in-sync manually, and we want to revisit using Poedit (like the Website), but we took the quick and easy approach for the sake of launching the MVP.  Once the Mobile App changes settle down, then we'll get the JSON schema into Poedit and crowd source the work for multiple languages

**Comment by zdmc23** [comment] 2020-02-11 06:01
Duplicate of #156

**Closed by zdmc23** 2020-02-11 06:01 UTC
Labels: question
