### ISSUE TITLE
Push Notifications to parse message and open to appropriate Post/Record

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#649] opened 2022-06-19 12:07 UTC
When a Push Notification is received, it displays a link to the actual record it is alerting the user to and the user will click on the push notification message and it will open to the appropriate Post/Record.

**Comment by zdmc23** [comment] 2022-07-05 12:57
Duplicate of #306

**Closed** 2022-08-05 01:21 UTC
