### ISSUE TITLE
Enhanced Edit/Save UI flow

### ISSUE THREAD

**Issue by cairocoder01** [DiscipleTools/disciple-tools-mobile-app#29] opened 2019-09-02 13:27 UTC
MexSurfer:
> Place an edit icon on the top right corner when editing is available. The text link is not that obvious and at times isn’t viewable. (ie. On some screens I found that if you scroll down, you then need to scroll back up to find and then click the edit link).

Using a text link within the body of the screen is very uncommon. A more common pattern would be to have the Edit link back in the header (as it was originally). This might cause some space issues with the share and follow actions in the future, but we can put those behind a smaller menu. Once in edit mode, that menu would be hidden and it would just be the Save link/button. Hitting the back button while in save mode should cancel the edits (not sure if we need to give a confirmation before cancelling).

Edit mode should maintain all of the tab layout of the contact/group detail screens.

![IMG_20190827_140827](https://user-images.githubusercontent.com/44169599/67470668-6db57000-f64e-11e9-9937-38d47ce444b3.jpg)

For reference of typical Edit flow on mobile: https://mobile-patterns.com/edit

**Comment by mikeallbutt** [comment] 2019-09-20 20:31
![image](https://user-images.githubusercontent.com/43966676/65357067-96fc5f80-dbbb-11e9-95ab-dda2a117f70c.png)

The save and cancel buttons are not visible.

**Comment by deividfdez** [comment] 2019-09-24 22:48
@cairocoder01 This issue has been solved

**Comment by cairocoder01** [comment] 2019-09-25 12:45
@deividfdez I don't see any changes in the app. Have these changes been pushed to Expo?

**Comment by mikeallbutt** [comment] 2019-10-23 16:29
This is how it could look with the cancel and save buttons at the top.

![screen details editings](https://user-images.githubusercontent.com/43966676/67414270-5a3fd180-f588-11e9-815a-c9e0e3c98e2a.png)

**Comment by mikeallbutt** [comment] 2019-10-23 16:40
Possibly have the edit icon (white pencil) in the header bar at the top and/or at the FAB so that the edit link is always accesible. 

![screen contact details](https://user-images.githubusercontent.com/43966676/67415015-c5d66e80-f589-11e9-9c2c-84141e98adef.png)

**Comment by cairocoder01** [comment] 2019-10-24 09:56
To consolidate the suggestions above, here is a design of what I would suggest that we do.

![image](https://user-images.githubusercontent.com/44169599/67474470-ce47ab80-f654-11e9-9eca-bea7d22f72ef.png)

## Requirement ##
* Edit link/icon is added to the right side of the header bar (and removed from the body of the screen)
* When in edit mode, header changes to Cancel and Save actions
  * Contact name no longer shows in header in order to make better use of the space
* In edit mode, tabs should still be visible and navigable in order to edit multiple fields in multiple tabs at once.
  * The exception is the Comments/Activity tab. There is no editable content in that tab, so it should not be visible in edit mode
* For the time being, quick actions will remain as the expanding FAB. A future issue could evaluate other options for that, but this issue will stay scoped to the access to the edit mode

**Comment by jl0325** [comment] 2019-11-27 14:19
I'm doing a new PR to fix text on edit mode like the next gif!:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/10079527/69730912-eea4d300-10f6-11ea-8039-4c262e2e4a71.gif)

**Comment by zdmc23** [comment] 2019-11-27 14:22
![8C52FB73-1B11-44B2-B9E8-AE9D8199F9E7](https://user-images.githubusercontent.com/191707/69731167-61ae4980-10f7-11ea-9d99-b92d06ed885f.png)

**Comment by jl0325** [comment] 2019-11-27 14:32
I don't have that problem

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/10079527/69731980-d1710400-10f8-11ea-845e-7e90181f1067.gif)

**Comment by zdmc23** [comment] 2019-11-27 14:38
You're not using the Contact or Group that I specified in my steps to reproduce.  We saw a similar issue previously where your code is using the `find()` function in a `map()` and then attempting to access a JSON property (`name` in this case), and if the `find()` result is `undefined`, then you will get an exception when attempting to access the property.  This is why I introduced the `safeFind()` function, and it should probably be implemented everywhere that you're executing a `find()` within a `map()` and then attempting to access a JSON property

```
const safeFind = (found, prop) => {
  if (typeof found === 'undefined') return '';
  return found[prop];
};
```

and used as follows:

```
                  <Text style={{ marginTop: 'auto', marginBottom: 'auto' }}>
                    {this.state.contact.subassigned
                      ? this.state.contact.subassigned.values
                          .map(
                            function(contact) {
                              return safeFind(
                                this.state.usersContacts.find(
                                  (user) => user.value === contact.value,
                                ),
                                'name',
                              );
                            }.bind(this),
                          )
                          .filter(String)
                          .join()
                      : ''}
                  </Text>
```

**Comment by deividfdez** [comment] 2019-11-27 15:42
@zdmc23 It would be good for DT Team to inform us when there is a change on the use of new  methods like Find --> Safe Find so that we can take it in consideration, since we didn´t have any notification the method was changed. We will make the necessary changes on the code, but please advice when there are new methods to avoid reprocessing or app crashes. We are committed on delivering acceptable PR´s.

**Comment by zdmc23** [comment] 2019-11-27 15:47
@deividfdez this was introduced to resolve issues introduced by your team. It is not causing any crash, it’s an option to resolve the issue introduced when a find returns undefined and you attempt to access a property (like “name”). Fix it however you’d like, but this goes back to an issue around the quality of code that you are delivering. I previously asked for test cases to understand how you were verifying on your end, but those were never provided. If you introduce a change that causes crash, it’s not enough to say: “it works for me, in this 1 scenario”

**Comment by zdmc23** [comment] 2019-11-28 01:33
![990362F1-0615-48BD-919F-3A40A32D537B](https://user-images.githubusercontent.com/191707/69769962-1aef3c80-1155-11ea-9d5d-e41f973553cf.png)
![D06AF9D6-E009-451A-B1D8-DC5A198C98C2](https://user-images.githubusercontent.com/191707/69769963-1aef3c80-1155-11ea-9ad1-9623feac2e50.png)
![7C783C2F-93E3-4878-B435-6960D0E75994](https://user-images.githubusercontent.com/191707/69769964-1aef3c80-1155-11ea-92dc-403cff7c197a.png)
![7F3CE514-BC5F-4AB8-86FD-5C2D0612FCD6](https://user-images.githubusercontent.com/191707/69769965-1aef3c80-1155-11ea-8d0c-db836eae0a99.png)

**Comment by jl0325** [comment] 2019-11-28 02:02
@zdmc23, I'll do a clone of development brach to test the merge, because I don't have that issue. I did the revision of my code in search of bad practices in the view like the .map followed by a .find to change it to a .safeFind but I don't have this structure. I will take the merge test in the development branch to get more information using your flow. Thank you very much for your cooperation.

**Comment by zdmc23** [comment] 2019-11-28 02:27
![A2C94351-9AEF-4B15-BA00-23E99F4B1512](https://user-images.githubusercontent.com/191707/69771973-a4563d00-115c-11ea-88c9-f91f31f2c5e7.png)

**Comment by zdmc23** [comment] 2019-11-28 02:28
Hi @jl0325 , Are you also testing with Expo?  I just tried on Android, and the white screen issue does not occur, but clicking `Edit` does cause it to crash on Android as well as iOS.  This is after I clear Expo data and cache

**Comment by zdmc23** [comment] 2019-11-28 02:31
![7A2502E9-1FBA-42B3-B5BE-FECC09E445BA](https://user-images.githubusercontent.com/191707/69772193-483fe880-115d-11ea-8978-0ca731e0afc6.png)

**Comment by mikeallbutt** [comment] 2019-11-28 02:37
> Hi @jl0325 , Are you also testing with Expo? I just tried on Android, and the white screen issue does not occur, but clicking `Edit` does cause it to crash on Android as well as iOS. This is after I clear Expo data and cache

I can confirm that I get the same issue on Android with a crash.
Steps to make it happen:
sign into dtappdemo instance
click an contact to view it
go to connections
click edit > white screen and crash.

**Comment by jl0325** [comment] 2019-11-28 02:43
I'm using Expo! I don't have that problem.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/69772615-6e19bd00-115e-11ea-9312-85b941612e70.gif)


@zdmc23  in the image of your first report say error in line 2611 from ContactsDetails is this line: 
![2611](https://user-images.githubusercontent.com/10079527/69772646-88ec3180-115e-11ea-83f4-6a7fd8c47fbe.PNG)

But I don't have that problem. I'm clone the development brach to do a review of this.

**Comment by zdmc23** [comment] 2019-11-28 02:47
@jl0325 Are you clearing the cache/data before running Expo on Android, and are you using the version from the `default` release channel (that's what's linked to our `development` branch)?

**Comment by mikeallbutt** [comment] 2019-11-28 02:50
Also, when creating a new contact, the new cancel button in the top left corner doesn't work. There is currently no Save button in the top right corner (I suspect that will be added shortly) and the old Save button at the bottom needs to be removed (if I understand the UI correctly).

**Comment by jl0325** [comment] 2019-11-28 02:52
> @jl0325 Are you clearing the cache/data before running Expo on Android, and are you using the version from the `default` release channel (that's what's linked to our `development` branch)?

I clone your development branch and do a 
npm i 
expo start -c

And remove expo app from my mobile and run the project.

**Comment by zdmc23** [comment] 2019-11-28 03:18
Can you try running from the link, rather than the command-line? https://expo.io/@discipletools/discipletoolsapp

**Comment by zdmc23** [comment] 2019-11-28 03:31
If you are unable to reproduce, then tomorrow we can reach out to some other folks to test.  So far, I have experienced the issue(s) on iOS (13.1.3) XR, and Android (7.1.1) Moto G4 Play, and Mike has Android, so it has been multiple devices, and also from Expo link and command-line.  Perhaps we can have a shared D.T account that we all use to confirm with, in additional to our own accounts

**Comment by jl0325** [comment] 2019-11-28 03:33
I clean my expo and use your DT app link!

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10079527/69775142-dc15b280-1165-11ea-9478-8f53903a05f6.gif)

**Comment by zdmc23** [comment] 2019-11-28 03:38
ok, we will ask some other people in the group to attempt to reproduce. Thx

**Comment by mikeallbutt** [comment] 2019-11-28 10:48
> Perhaps we can have a shared D.T account that we all use to confirm with, in additional to our own accounts

I think that will be very helpful. A user account so we are all using the same role within DT. A new user could be made or just convert an existing one.

**Comment by jl0325** [comment] 2019-11-28 13:00
> Perhaps we can have a shared D.T account that we all use to confirm with, in additional to our own accounts


That is a very good idea. Can you share one on Slack to continue with the tests?

**Comment by zdmc23** [comment] 2019-11-29 20:02
Verified for Contacts, but crashes when I select `Yet Another Group` Group and click `Edit`

![DD669EC7-8566-4DCB-930F-3BF6060992EE](https://user-images.githubusercontent.com/191707/69888326-4723ce00-12b9-11ea-8645-97fb9d9d3386.png)

**Comment by zdmc23** [comment] 2019-11-29 23:47
Members Tab enables you to take edit actions (i.e., click `X` or interact with the  Add input field, these items should be display only (a list with no `X`s or input) until the user clicks `Edit`

Additionally, clicking `Edit` and taking some action (delete or add, or both) and clicking `Save` does not take user back to the View mode. `Cancel` and `Save` remain no matter how many times `Save` is clicked

![4F5FDC43-2514-4504-9A9E-406CF9C3933D](https://user-images.githubusercontent.com/191707/69892903-7b5ab700-12d8-11ea-9223-f35410e52159.png)
![F30ABC3D-5EF9-4778-8639-DFA4A27A109C](https://user-images.githubusercontent.com/191707/69892904-7b5ab700-12d8-11ea-8ee4-77ad0432ac1d.png)

**Comment by zdmc23** [comment] 2019-12-07 03:07
Verified. 

![BBA77CAD-D105-4757-B7FB-4575DAC278D3](https://user-images.githubusercontent.com/191707/70368092-c6467280-1874-11ea-91e3-1c68f3ebf42b.png)
![C38A4427-4174-4EF4-95EB-A4F6152BB69B](https://user-images.githubusercontent.com/191707/70368093-c6467280-1874-11ea-9439-95029f80cca6.png)

**Closed by zdmc23** 2019-12-07 03:07 UTC
Labels: enhancement, in-progress
