### ISSUE TITLE
Mixed data after switching to a different user

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#734] opened 2023-02-07 11:41 UTC
When you log out of one user and sign in with a different user and both are on different servers and are different instances, then the data is mixed - it shows some data from the first now logged out instance and in other places it shows the data from the new now logged in user.

In the attached image the correct data is what is in the activity tile.

The favorite contact count was 5 but shows 10 but should be 23.

The favourite group count was 4 but should be 12.

![IMG_20230207_053345.jpg](https://user-images.githubusercontent.com/43966676/217235420-78c21819-52a5-449b-aa33-559d2ba28c63.jpg)

**Comment by mikeallbutt** [comment] 2023-02-07 11:47
On the list contact screen it shows a blend of data. In the attached image the items with the orange make are from the logged out user.

![IMG_20230207_054357.jpg](https://user-images.githubusercontent.com/43966676/217236582-893125eb-78dc-40b2-8254-fb009e583615.jpg)

The groups list screen actually only shows old data and no groups from the current logged in user.

**Comment by mikeallbutt** [comment] 2023-02-07 11:55
If you click on an old record item it will open the old record and display the details but after about 5 seconds the screen will reload with data from the new logged in instance.

**Comment by zdmc23** [comment] 2023-03-20 02:57
Duplicate of #710

**Closed by zdmc23** 2023-03-20 02:57 UTC
