### ISSUE TITLE
Scroll up to show options on dropdown select

### ISSUE THREAD

**Issue by yorkaspacher** [DiscipleTools/disciple-tools-mobile-app#25] opened 2019-08-22 14:16 UTC
When you tap a drop down list field to select items, keyboard pops up and aligns with bottom of text box, but you can't see the items in the list without manually scrolling up. I think it would be helpful to have it scroll up either to top of screen or at least a little to reveal list you are selecting from. Seeing nothing but a blank text box makes it feel like you have to type something there... 
![image](https://user-images.githubusercontent.com/47872338/63522169-d30da900-c4c5-11e9-8cec-aca600ceae4b.png)
![image](https://user-images.githubusercontent.com/47872338/63522192-e02a9800-c4c5-11e9-8b36-a28bcef31e38.png)

**Comment by deividfdez** [comment] 2019-09-24 22:22
@yorkaspacher This issue has been fixed, when a field is selected, an automatic scroll to the field location is performed

**Comment by zdmc23** [comment] 2019-10-20 14:40
@yorkaspacher please review when you have the chance, and Close if satisfied. Thx!

**Comment by yorkaspacher** [comment] 2019-10-23 12:47
Sorry - this problem hasn't been addressed. The issue states that the problem IS that the keyboard aligns to the bottom of the field text box - you can't see that there are options to scroll through. Having the keyboard pop up (which it should, because you can type), and align to the box makes it seem you *have to* type something - but if what you're looking for is in the list, maybe even at the top of the list, you don't have to type or search, you just select it. But you can't perceive that from the way it's working now.

**Comment by zdmc23** [comment] 2020-02-11 04:59
Duplicate of #66 (to be fixed in Sprint 14)

**Closed by zdmc23** 2020-02-11 04:59 UTC
Labels: bug, needs review
