### ISSUE TITLE
View Custom Filters in Mobile App

### ISSUE THREAD

**Issue by ericchen59** [DiscipleTools/disciple-tools-mobile-app#474] opened 2020-10-08 04:45 UTC
As a mobile app user (multiplier), I want to be able to see the Custom Filters that I have saved on the DT web version, so that I can quickly see custom views of my contacts database.

**Acceptance Criteria**
- [ ] DT mobile app user can see and select the same options for Custom Filters as they would if they were using DT web version

**DT Web - Custom Filters are accessed here**
<img width="1189" alt="Screen Shot 2020-10-08 at 12 41 18 AM" src="https://user-images.githubusercontent.com/26180602/95415843-5626d400-08ff-11eb-9177-ab79dfd04527.png">

**DT Mobile - Customer Filters could be placed here**
![IMG_2984](https://user-images.githubusercontent.com/26180602/95415881-70f94880-08ff-11eb-9215-674032367848.jpg)

@mikeallbutt - can you advise if this is a good place to find Custom Filters in the mobile app?

cc @zdmc23 and @ahillbilly

**Comment by ahillbilly** [comment] 2020-10-08 07:55
I had this on my list too.  I think where you highlighted is the natural place for it.

Secondary question (for another issue?) - Do we allow (add functionality for) creation and saving of custom filters within the app?  Or do we keep that as a web based function?

**Comment by ericchen59** [comment] 2020-10-08 11:47
I do think that creation and saving of custom filters in the app would be a natural next step. But a little unsure on the size effort it would take.

@zdmc23 any insight on how much effort might increase by if we bundle this issue + function for creation and saving of custom filters (i.e. 1.5x, 2x, 5x?)

**Comment by ahillbilly** [comment] 2020-10-08 11:56
I’d probably separate…

I’m also curious why the default filters that they have implemented don’t operate the same as the web… they’re somehow querying differently.  Same filter in mobile and web aren’t yielding the same results.

I’ll try to find and post an example with test data, but have seen it with live data.

**Comment by raschdiaz** [comment] 2020-11-05 22:57
Hi @ericchen59 @ahillbilly @corsacca we found a problem trying to implement the following filter:

![image](https://user-images.githubusercontent.com/16809967/98305026-118a6900-1f8f-11eb-9b00-3d2fe4e41a3e.png)

This filter its related to the 'share' data of the contact, but in the current contact list (persisted in the app), this information is not present.

This is the value used to filter the list:

![image](https://user-images.githubusercontent.com/16809967/98305434-d9cff100-1f8f-11eb-8571-c9577261f4df.png)

It is possible that this problem occurs with other filters, since we depend on the filter values to match the contact values.

We made a function to detect the filter values in the contact/group data lists according to the value type. This results in getting the same data like web behavior.

@ahillbilly to clarify the behavior, we have to do the filters "from scratch" in the mobile app to support the OFFLINE mode.

**Comment by corsacca** [comment] 2020-11-06 08:45
For filters that don't directly match fields: is it possible to not support the in offline mode?

**Comment by raschdiaz** [comment] 2020-11-06 19:48
We can try to omit them to not show them if the filters does not return registers. We prefer to add this to ONLINE/OFFLINE mode to avoid the user select a filter that could not work (As mentioned in our previous comment).

What do you think about this?.

**Comment by ahillbilly** [comment] 2020-11-07 12:44
Whether we hide the filter completely in offline mode or grey it out with an icon indicating it isn't available in offline mode, I think that the solution: Don't offer a filter in offline mode that doesn't work correctly in offline mode - is correct.  We can discuss whether to add them grey'd out or hide them completely as a separate issue, but I believe either of these would allow you to complete this issue satisfactorily.

**Comment by ericchen59** [comment] 2020-11-10 05:36
> Whether we hide the filter completely in offline mode or grey it out with an icon indicating it isn't available in offline mode, I think that the solution: Don't offer a filter in offline mode that doesn't work correctly in offline mode - is correct. We can discuss whether to add them grey'd out or hide them completely as a separate issue, but I believe either of these would allow you to complete this issue satisfactorily.

@raschdiaz - is the above sufficient direction? Let us know! Thanks

**Comment by raschdiaz** [comment] 2020-11-10 22:26
Hi @ahillbilly @ericchen59 We implemented this behavior in the mobile app, but we found the following behavior:

If the user log-in in the app (ONLINE MODE), get the all the filters (including the ones that not return contacts/groups records), and after this switch to the OFFLINE MODE, the filters that not return contacts/groups records, will not disappear. 
This happens because the mobile app maps the filters config in the user login process.

To resolve that, we consider to detect the mobile ONLINE/OFFLINE mode change to retrieve the updated data of filters or remap them to only show the filters that return contacts/groups records.

What do you think about this?.

**Comment by ericchen59** [comment] 2020-11-11 02:57
> Hi @ahillbilly @ericchen59 We implemented this behavior in the mobile app, but we found the following behavior:
> 
> If the user log-in in the app (ONLINE MODE), get the all the filters (including the ones that not return contacts/groups records), and after this switch to the OFFLINE MODE, the filters that not return contacts/groups records, will not disappear.
> This happens because the mobile app maps the filters config in the user login process.
> 
> To resolve that, we consider to detect the mobile ONLINE/OFFLINE mode change to retrieve the updated data of filters or remap them to only show the filters that return contacts/groups records.
> 
> What do you think about this?.

I would lean towards the option of "detect the mobile ONLINE/OFFLINE mode change to retrieve the updated data of filters." However, I will defer to @corsacca and @ahillbilly, they may have a better sense of the web users' expectation.

**Comment by corsacca** [comment] 2020-11-11 09:40
@raschdiaz how do you determine if a filter works in offline mode? It think you are right that we need to run some checks when displaying a page to check if the user is offline or online.

**Comment by raschdiaz** [comment] 2020-11-11 13:19
@corsacca actually, in the login process, the app mobile do a request to get the filters config, in this process we check the OFFLINE state of app, if true, only return the filters that show records (specifically in the reducer).

**Comment by raschdiaz** [comment] 2020-11-11 23:40
Hi @ericchen59 @ahillbilly @corsacca @zdmc23 see the following video with the implementation:

[https://drive.google.com/file/d/1jzNgHhvI3A31IDI_Suk9lJat-aw9s3Zx/view?usp=sharing](https://drive.google.com/file/d/1jzNgHhvI3A31IDI_Suk9lJat-aw9s3Zx/view?usp=sharing)

**Comment by zdmc23** [comment] 2020-11-23 02:20
This no longer works, and may be related to #497 implementation.

Observed on iOS 14 and Android 7.1

Steps to reproduce:
1. Clear Expo cache/data (delete/re-install Expo app on iOS)
1. Login
1. Select "Custom Filters" ("My Contacts" also no longer working!)
1. Select "Tunis" (or any available Custom Filter)
1. Observe no contacts are displayed on the app, but if you see attached screenshots, there are available Contacts which are assigned to my user account

(If you attempt to refresh, then the Filter is removed and all Contacts are refreshed - see #508)

![tuni-works](https://user-images.githubusercontent.com/191707/99924467-699fca00-2d08-11eb-856c-98f21a785894.png)

![tuni-filter](https://user-images.githubusercontent.com/191707/99924477-78867c80-2d08-11eb-9fc4-eb826491ad81.png)

![yay-works](https://user-images.githubusercontent.com/191707/99924495-8cca7980-2d08-11eb-9231-ef6a2d355f30.PNG)

![yay-broke](https://user-images.githubusercontent.com/191707/99924499-905e0080-2d08-11eb-8dbf-346afbbf3d07.png)

**Comment by raschdiaz** [comment] 2020-11-23 13:42
Hi @ zdmc23 seeing this, we consider that we need an example of each custom filter to be able to perform tests and verify that they work correctly

**Comment by ahillbilly** [comment] 2020-11-24 09:18
@raschdiaz ,  Have you guys played with how the custom filters work on the web version?  The YouTube channel has a tutorial for use of custom filters.  Please watch it to fully understand the functionality that you're mimicking on mobile.

https://www.youtube.com/watch?v=n6ZiQmBGdr8&list=PLAF7wU9d7FkL7EVC57EwJmRoqnaEBae-x&index=3

Because the filters are custom creations saved on the web version, they will be different for each user.  Each user has their own custom filters and can add and delete them on the web interface.  This issue is to reflect those filters on mobile.

**Comment by raschdiaz** [comment] 2020-11-24 19:56
@ahillbilly Yes, as we understand, in the web platform, filters are used through requests (GET).

In order to support **OFFLINE** mode, the mobile app performs a 'handmade' process (maps the filters obtained from the API so that they match with the JSON structure of the contacts / groups persisted in the app, and do the search according to this), and thus they are returned results.

**Comment by ericchen59** [comment] 2020-12-03 04:46
Progress note: As of today, this will issue will present itself for the user who has over 1000 contacts. I'm going to take the liberty to assume this will be a issue best solved at a future date, as the mobile app matures.

**Closed** 2021-02-08 06:44 UTC
Labels: bug, feature, invalid
