### ISSUE TITLE
New contact / group: edit not available after first save

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#165] opened 2019-12-13 20:20 UTC
When creating a new contact or group, there is no edit icon available after clicking save and arriving at the next screen.

![Screenshot_20191213-135802](https://user-images.githubusercontent.com/43966676/70829528-9981e600-1db3-11ea-9e85-41eca4aaeaf2.png)
![Screenshot_20191213-141615](https://user-images.githubusercontent.com/43966676/70829529-9981e600-1db3-11ea-85fd-fda21b33adb9.png)

**Comment by ahillbilly** [comment] 2020-02-06 10:27
I also reproduced this error - tested on iPhone 10

**Comment by raschdiaz** [comment] 2020-02-21 12:48
Hi @ahillbilly , this issue was resolved in the first PR Sprint 14, can you confirm if works please?.

**Comment by ahillbilly** [comment] 2020-02-25 10:55
@raschdiaz I'm unable to test this due to the Expo issue that was highlighted yesterday.  I'm currently locked out.

**Comment by zdmc23** [comment] 2020-03-01 21:46
I have confirmed that `Edit` is available after creating a New Contact

![65FD25A6-8125-4568-BBBF-1789D72324CF](https://user-images.githubusercontent.com/191707/75634455-17e46c00-5bdc-11ea-8a8d-13ee8b2863a6.png)

@ahillbilly Please delete the Expo app, reinstall, and re-login. That should be sufficient to regain access. (I also have to do it far too often as a result of various login issues).

**Closed by zdmc23** 2020-03-01 21:46 UTC
Labels: bug

**Comment by ahillbilly** [comment] 2020-03-02 16:04
I have confirmed that this is fixed.
