### ISSUE TITLE
Remove back arrow when in edit mode

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#61] opened 2019-10-23 17:58 UTC
The back arrow should be disabled when in edit mode. 

![screen details editing](https://user-images.githubusercontent.com/43966676/67420711-c3c5dd00-f594-11e9-947d-ea5e44054c91.png)

Pressing the back arrow should only take someone back to the previous view, and not skip directly to the contact or group page.

**Comment by cairocoder01** [comment] 2019-10-24 15:53
This ends up being a duplicate of the issue for modifying the Edit flow #29

**Closed by cairocoder01** 2019-10-24 15:53 UTC
