### ISSUE TITLE
Save results in 400 error

### ISSUE THREAD

**Issue by zdmc23** [DiscipleTools/disciple-tools-mobile-app#396] opened 2020-08-04 03:15 UTC
Attempted `Save` of a Contact and 1st attempt fails with 400 error while 2nd attempt consistently works.  It is occurring with multiple Contacts, but specifically in the "dtdemo" instance (not "dtappdemo").  For at least 1 `Group` I cannot successfully save (always results in 400 error).

Observed on iOS 13.6

Steps to reproduce for `Contact`:
1. Log into https://dtdemo.disciple.tools
1. Select a `Contact` (eg, "Seeker of Truth")
1. Click `Edit`
1. Edit the Phone Number
1. Click `Save`
1. Observe 400 error
1. Click `Save` (a 2nd time)
1. Observe success

Steps to reproduce for `Group`:
1. Log into https://dtdemo.disciple.tools
1. Select a `Group` (eg., "Hans Group 2")
1. Click `Edit`
1. Add a new `Address` line (eg, "123 easy st")
1. Click `Save`
1. Observe 400 error
1. Click `Save` (a 2nd, 3rd, 4th, ... time)
1. Observe continued 400 error

![D5AD310A-DB61-43D2-A31B-10C20C0E243E](https://user-images.githubusercontent.com/191707/89249047-2dbce980-d5df-11ea-9198-7b9c3b052cd6.png)

![424314FE-3111-43BC-8C56-99237FF03109](https://user-images.githubusercontent.com/191707/89249615-a7a1a280-d5e0-11ea-8ee2-7a3ea9f45f94.png)

**Comment by raschdiaz** [comment] 2020-08-13 02:44
We see this issue while we are working in the #400 issue. With Sentry implementation, We can see a more detailed cause:

[https://sentry.io/organizations/disciple-tools/issues/1810149131/?project=5356329&query=is%3Aunresolved&statsPeriod=14d](https://sentry.io/organizations/disciple-tools/issues/1810149131/?project=5356329&query=is%3Aunresolved&statsPeriod=14d)

![image](https://user-images.githubusercontent.com/16809967/90088539-c987dd00-dce4-11ea-9951-dc3acd1af445.png)

For some reason the group save end-point throw this error, that seems weird to me because I tested sending the same JSON using Postman, but work correctly.

When I send the end-point again, works as expected.

**Comment by raschdiaz** [comment] 2020-08-13 15:35
Hi @zdmc23 We can reproduce the error in the save group end-point, for some reason, the end-point return this error when the **assigned_to** field its updated:

![image](https://user-images.githubusercontent.com/16809967/90154885-47350280-dd50-11ea-8aa8-ded5a2075881.png)

The field its updated correctly:

![image](https://user-images.githubusercontent.com/16809967/90155136-967b3300-dd50-11ea-8319-eb61f91ba405.png)


But, if I send the request again:

![image](https://user-images.githubusercontent.com/16809967/90154953-5b78ff80-dd50-11ea-978c-e297d80a7361.png)

I will do another test with a contact save.

**Comment by raschdiaz** [comment] 2020-08-13 19:50
We found the same error in the **dtdemo** instance adding a new address to the group:

![image](https://user-images.githubusercontent.com/16809967/90180104-1c5ca580-dd74-11ea-84bf-adf2c01cdd48.png)

Like the previous test, the end-point return a 500 error, but the data its saved correctly:

![image](https://user-images.githubusercontent.com/16809967/90180246-4e6e0780-dd74-11ea-817b-18a1f056a869.png)

**Comment by zdmc23** [comment] 2020-08-14 12:25
Hi @raschdiaz , are you able to reproduce using your own local development instances?  Because then you would be able to review the WordPress debug logs.  Otherwise, we will need assistance from @corsacca because I do not have access to the servers hosting these D.T instances

**Comment by corsacca** [comment] 2020-08-14 15:41
Here is the error. I'm looking in to it.

PHP Fatal error:  Uncaught ExponentPhpSDK\Exceptions\UnexpectedResponseException: Unexpected response was received from Expo API. in /nas/content/live/dtappdemo/wp-content/plugins/disciple-tools-mobile-app-plugin/vendor/alymosul/exponent-server-sdk-php/lib/Expo.php:206
Stack trace:
#0 /nas/content/live/dtappdemo/wp-content/plugins/disciple-tools-mobile-app-plugin/vendor/alymosul/exponent-server-sdk-php/lib/Expo.php(112): ExponentPhpSDK\Expo->executeCurl(Resource id #608)
#1 /nas/content/live/dtappdemo/wp-content/plugins/disciple-tools-mobile-app-plugin/includes/functions.php(158): ExponentPhpSDK\Expo->notify(Array, Array)
#2 /nas/content/live/dtappdemo/wp-includes/class-wp-hook.php(287): DT_Mobile_App_Plugin_Functions->send_notification_on_channels(13, Array, 'changes', Array)
#3 /nas/content/live/dtappdemo/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#4 /nas/content/live/dtappdemo/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /nas/content/live/dtappdemo/wp-content/themes/disciple-tools-t in /nas/content/live/dtappdemo/wp-content/plugins/disciple-tools-mobile-app-plugin/vendor/alymosul/exponent-server-sdk-php/lib/Expo.php on line 206

**Comment by corsacca** [comment] 2020-08-14 16:48
Fixed with: https://github.com/DiscipleTools/disciple-tools-mobile-app-plugin/releases/tag/v1.8

**Closed** 2020-08-26 13:01 UTC
Labels: bug
