### ISSUE TITLE
PlaceHolder misspelled

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#273] opened 2020-03-16 23:42 UTC
In 122 locations in the app code, there are references to 'PlacheHolder'. Most of these are in the language files.

The word should be 'PlaceHolder' and not 'PlacheHolder'

Fixing this now will avoid bad referencing down the track.

**Comment by zdmc23** [comment] 2020-03-19 21:19
Duplicate of #266

**Closed by zdmc23** 2020-03-19 21:19 UTC
