### ISSUE TITLE
Progress icons are hard to see/read when not activated.

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#352] opened 2020-06-19 02:21 UTC
The text for the icons for the Faith Milestones (of a contact) and the Church Health (of a group) and hard to read when the milestone is not activated.

**Comment by zdmc23** [comment] 2020-06-19 03:29
Duplicate of #260

**Closed by zdmc23** 2020-06-19 03:29 UTC
