### ISSUE TITLE
Unrequested updates logged

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#419] opened 2020-08-21 16:46 UTC
In instance dtappdemo: 

An unrequested contact name was updated when adjusting the phone number or age or gender of the contact "señora saira". When doing a second test later, it also logged info about the status and assigned to fields - neither of which were changed.

Setting the age for "Excel issue 19" also logged Gender as being nothing.

**Comment by zdmc23** [comment] 2020-08-26 07:02
Duplicate of #397

**Closed** 2023-03-20 02:58 UTC
Labels: duplicate
