### ISSUE TITLE
Choose contact type when creating a new contact record 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#551] opened 2021-01-29 11:36 UTC
Have the ability to set the contact type when creating a new contact record.

And be able to change it after the record is created.

**Comment by mikeallbutt** [comment] 2022-06-19 12:35
The ability to set it is available but not the option to see it nor edit it.

**Comment by zdmc23** [comment] 2023-03-20 02:43
Duplicate of #637

**Closed by zdmc23** 2023-03-20 02:43 UTC
Labels: feature
