### ISSUE TITLE
Contact Status is incorrect/different from list

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#272] opened 2020-03-15 04:09 UTC
When viewing some contact records, in the list the status of the record is active, but when you go to view the details, it switches over to say "new contact" as the status.

https://www.youtube.com/watch?v=kYymbv2t00A

**Comment by zdmc23** [comment] 2020-05-27 14:07
Duplicate of #283

**Closed by zdmc23** 2020-05-27 14:07 UTC
Labels: invalid
