### ISSUE TITLE
Edit Group: Groups tab: child field: auto-suggest not visible 

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#138] opened 2019-11-29 13:19 UTC
As can be seen in this first image, the suggested groups are not visible. The page needs to scroll up to show the list.

![Screenshot_20191129-065901](https://user-images.githubusercontent.com/43966676/69870977-2f2b5a80-1277-11ea-97fd-d0d8a0d446c9.png)

If I manually scroll up I can see this:
![Screenshot_20191129-071338](https://user-images.githubusercontent.com/43966676/69871435-651d0e80-1278-11ea-815b-61de0fff9af3.png)

But the full list is still not visible unless I remove the keyboard.
![Screenshot_20191129-071313](https://user-images.githubusercontent.com/43966676/69871484-8d0c7200-1278-11ea-90e6-bd3aa747bb13.png)

**Comment by mikeallbutt** [comment] 2019-11-30 06:21
This issue is what was mentioned in issue #66

**Comment by mikeallbutt** [comment] 2019-12-13 06:21
This bug should be added to the next sprint.

**Comment by zdmc23** [comment] 2020-02-11 04:49
Duplicate of #66

**Closed by zdmc23** 2020-02-11 04:49 UTC
