### ISSUE TITLE
Replace inconsistent icons

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-mobile-app#278] opened 2020-03-19 15:55 UTC
In some places, some of the fields use different icons to what is seen on the DT website. 

Replace the icons with the same as the website.

- [ ] Gender
- [ ] Source

Here are the new icons:

![gender](https://user-images.githubusercontent.com/43966676/77086696-b7b93c80-69c7-11ea-9a63-84423a8c1b5c.png)
![source](https://user-images.githubusercontent.com/43966676/77086702-bb4cc380-69c7-11ea-83dd-bdfb0dfdb52e.png)

**Comment by zdmc23** [comment] 2020-07-11 21:39
Duplicate of #68

**Closed by zdmc23** 2020-07-11 21:39 UTC
Labels: UI/style
